name: prebuild-test

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Prebuild runtime'
        type: choice
        required: true
        default: node
        options:
          - node
          - electron
      targets:
        description: 'Runtime versions (targets)'
        required: true
        default: -t 18.0.0
      ubuntu-18.04:
        description: 'Test on ubuntu-18.04'
        type: boolean
        default: true
      windows-2019:
        description: 'Test on windows-2019'
        type: boolean
        default: true
      macos-latest:
        description: 'Test on macos-latest'
        type: boolean
        default: true

jobs:
  input-setup:
    name: Preparing tests
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.set-platforms.outputs.platforms }}
    steps:
      - name: Setting up platform matrix
        id: set-platforms
        run: |
          INPUTS='${{ toJSON(inputs) }}'
          PLATFORMS='{"os":[]}'
          
          for os in 'ubuntu-18.04' 'windows-2019' 'macos-latest'
          do
            if [ "$(jq ".[\"$os\"]" <<< "$INPUTS")" = "true" ]; then PLATFORMS=$(jq -c ".os += [\"$os\"]" <<< "$PLATFORMS"); fi
          done
          
          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT

  prebuild-test:
    strategy:
      matrix: ${{ fromJSON(needs.input-setup.outputs.platforms) }}
    name: Testing prebuild on ${{ matrix.os }}
    needs: input-setup
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --ignore-scripts
      - run: npx --no-install prebuild -r ${{ inputs.runtime }} ${{ inputs.targets }} --include-regex 'better_sqlite3.node$'
