name: prebuild-test

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Prebuild runtime'
        required: true
        default: node
      targets:
        description: 'Runtime versions'
        required: true
        default: -t 16.0.0
      platform:
        description: 'Platform'
        required: true
        default: 'ubuntu-18.04'
        type: choice
        options:
          - ubuntu-18.04
          - macos-latest
          - windows-2019

jobs:
  prebuild-test:
    name: Testing prebuild on ${{ github.event.inputs.platform }}
    runs-on: ${{ github.event.inputs.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --ignore-scripts
      - run: npx --no-install prebuild -r ${{ github.event.inputs.runtime }} ${{ github.event.inputs.targets }} --include-regex 'better_sqlite3.node$'
