name: test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          - windows-latest
        node:
          - 10
          - 12
          - 14
          - 16
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts
      - run: npm run build-debug
      - run: npm test

  test-alpine:
    name: Testing Node 16 on apline
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v2
      - run: apk add build-base git python3 --update-cache
      - run: npm install --ignore-scripts
      - run: npm run build-debug
      - run: npm test

  test-arm64-alpine:
    name: Testing Node 16 on apline (arm64)
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - run: |
          docker run --rm --entrypoint /bin/sh --platform linux/arm64 node:16-alpine -c "apk add build-base git python3 --update-cache && \
          git clone https://github.com/JoshuaWise/better-sqlite3 && \
          cd better-sqlite3 && \
          npm install --ignore-scripts && \
          npm run build-debug && \
          npm test
