name: test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          - windows-latest
        node:
          - 10
          - 12
          - 14
          - 16
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts
      - run: npm run build-debug
      - run: npm test

  test-alpine-linux:
    name: Testing Node 16 on Alpine-Linux
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v2
      - run: apk add build-base git python3 --update-cache
      - run: npm install --ignore-scripts
      - run: npm run build-debug
      - run: npm test

  test-alpine-linux-arm64:
    name: Testing Node 16 on Alpine-Linux (arm64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/arm64 node:16-alpine -c "\
          apk add build-base git python3 --update-cache && \
          cd /tmp/project && \
          npm install --ignore-scripts && \
          npm run build-debug && \
          npm test"

  test-linux-arm:
    strategy:
      matrix:
        arch:
          - arm/v7
          - arm64
    name: Testing Node 16 on Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/${{ matrix.arch }} node:16 -c "\
          cd /tmp/project && \
          npm install --ignore-scripts && \
          npm run build-debug && \
          npm test"
